name: big_data_env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.25=h0dcde21_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py39h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - contourpy==1.3.0
      - cycler==0.12.1
      - fonttools==4.60.1
      - graphframes==0.6
      - imageio==2.37.2
      - importlib-resources==6.5.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - matplotlib==3.9.4
      - networkx==3.2.1
      - nose==1.3.7
      - numpy==2.0.2
      - packaging==25.0
      - pillow==11.3.0
      - py4j==0.10.9.7
      - pyparsing==3.2.5
      - pyspark==3.5.0
      - python-dateutil==2.9.0.post0
      - scikit-image==0.24.0
      - scipy==1.13.1
      - simpleitk==2.5.3
      - six==1.17.0
      - tifffile==2024.8.30
      - trimesh==4.9.0
      - zipp==3.23.0
prefix: /home/lgh/anaconda3/envs/default_env
